# Generated by Django 3.1.2 on 2020-11-26 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.FloatField(choices=[(-23, 'Дніпро'), (-23, 'Донецьк'), (-20, 'Івано-Франківськ'), (-22, 'Київ'), (-23, 'Кривий ріг'), (-25, 'Луганськ'), (-19, 'Львів'), (-16, 'Симферополь'), (-18, 'Одеса'), (-23, 'Харків')], default=-22)),
                ('choice1', models.IntegerField(default=11)),
                ('choice2', models.IntegerField(default=12)),
                ('inhabitants', models.IntegerField(default=1)),
                ('shower_use', models.IntegerField(default=1)),
                ('water_usage_norm', models.FloatField(default=100.0)),
                ('bath_use', models.FloatField(default=1.0)),
                ('bath_temperature', models.FloatField(default=37.0)),
                ('shower_temperature', models.FloatField(default=30.0)),
                ('tank_temperature', models.FloatField(default=60.0)),
                ('time_of_tank_heating', models.FloatField(default=120.0)),
                ('heat_losses_of_building', models.FloatField(default=0.0839)),
                ('house_area', models.FloatField(default=75.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2000)])),
                ('air_temperature', models.FloatField(default=20.0)),
                ('air_temperature_out', models.FloatField(choices=[(-23, 'Дніпро'), (-23, 'Донецьк'), (-20, 'Івано-Франківськ'), (-22, 'Київ'), (-23, 'Кривий ріг'), (-25, 'Луганськ'), (-19, 'Львів'), (-16, 'Симферополь'), (-18, 'Одеса'), (-23, 'Харків')], default=-22)),
                ('taryph', models.FloatField(default=1444.0)),
                ('enter_temperature', models.FloatField(default=15.0)),
                ('exit_temperature', models.FloatField(default=85.0)),
                ('time_vol_heating', models.FloatField(default=10.0)),
                ('vugil_am', models.FloatField(default=0.0001792)),
                ('vugil_cost', models.FloatField(default=4234)),
                ('gas_am', models.FloatField(default=0.1075)),
                ('gas_cost', models.FloatField(default=5.97)),
                ('drowa_am', models.FloatField(default=0.000287)),
                ('drowa_cost', models.FloatField(default=850)),
                ('pelet_am', models.FloatField(default=0.0001953)),
                ('pelet_cost', models.FloatField(default=4650)),
                ('elec_am', models.FloatField(default=1.01)),
                ('elec_cost', models.FloatField(default=1.68)),
            ],
        ),
    ]
