# Generated by Django 3.1.2 on 2020-11-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201126_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='task2',
            name='m_x2',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='task2',
            name='choice1',
            field=models.IntegerField(default=10),
        ),
    ]
